# Generated by Django 3.2.16 on 2022-12-25 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_room_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField()),
                ('room_code', models.CharField(max_length=8)),
                ('prompt_text', models.TextField()),
                ('prompt_key', models.IntegerField()),
                ('assigned_user', models.TextField()),
                ('assigned_round', models.IntegerField()),
            ],
        ),
    ]
