# Generated by Django 3.2.16 on 2022-12-25 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='assigned_round',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='assigned_user',
            field=models.TextField(default=None),
        ),
    ]
