# Generated by Django 3.2.16 on 2023-02-06 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20221225_2345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, unique=True)),
                ('room_code', models.CharField(max_length=8)),
                ('alias', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='prompt',
            name='user',
        ),
        migrations.AddField(
            model_name='prompt',
            name='host',
            field=models.CharField(default='None', max_length=50),
            preserve_default=False,
        ),
    ]
