# Generated by Django 3.2.16 on 2023-02-06 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20230206_0407'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='user',
            field=models.CharField(default='None', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alias',
            name='user',
            field=models.CharField(max_length=50),
        ),
    ]
