# Generated by Django 3.2.16 on 2023-02-06 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20230206_0408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='guest_can_pause',
        ),
        migrations.RemoveField(
            model_name='room',
            name='votes_to_skip',
        ),
        migrations.AddConstraint(
            model_name='alias',
            constraint=models.UniqueConstraint(fields=('alias', 'room_code'), name='Unique Room Aliasing'),
        ),
    ]
