# Generated by Django 3.2.16 on 2023-02-15 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20230206_2210'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='alias',
            name='Unique Room Aliasing',
        ),
        migrations.AddField(
            model_name='room',
            name='gamestate',
            field=models.CharField(default='queue', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='alias',
            constraint=models.UniqueConstraint(fields=('alias', 'room_code'), name='unique_aliasing'),
        ),
    ]
