# Generated by Django 3.2.16 on 2023-03-16 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alias_ready'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alias',
            name='user',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
