# Generated by Django 3.2.16 on 2023-03-16 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_alias_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prompt',
            name='assigned_round',
        ),
        migrations.RemoveField(
            model_name='prompt',
            name='assigned_user',
        ),
        migrations.AddField(
            model_name='prompt',
            name='assigned_user_1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='prompt',
            name='assigned_user_1_song_choice',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='prompt',
            name='assigned_user_1_votes',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='prompt',
            name='assigned_user_2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='prompt',
            name='assigned_user_2_song_choice',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='prompt',
            name='assigned_user_2_votes',
            field=models.IntegerField(null=True),
        ),
    ]
