# Generated by Django 3.2.16 on 2023-03-16 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20230316_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_round',
            field=models.IntegerField(default=0),
        ),
    ]
