# Generated by Django 3.2.16 on 2023-06-22 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_room_room_round'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='alias',
            name='unique_aliasing',
        ),
        migrations.AlterField(
            model_name='prompt',
            name='assigned_user_1_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='assigned_user_2_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='alias',
            constraint=models.UniqueConstraint(fields=('room_code', 'alias'), name='unique_aliasing'),
        ),
    ]
