# Generated by Django 3.2.16 on 2023-09-10 04:43

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_prompt_submitted'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptAssignments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_user', models.CharField(max_length=50)),
                ('room_code', models.CharField(max_length=8)),
                ('prompt_unique_id', models.CharField(default=api.models.generate_room_code, max_length=8, unique=True)),
                ('assigned_user_song_choice', models.TextField(null=True)),
                ('assigned_user_votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='prompt',
            name='assigned_user_1',
        ),
        migrations.RemoveField(
            model_name='prompt',
            name='assigned_user_1_song_choice',
        ),
        migrations.RemoveField(
            model_name='prompt',
            name='assigned_user_1_votes',
        ),
        migrations.RemoveField(
            model_name='prompt',
            name='assigned_user_2',
        ),
        migrations.RemoveField(
            model_name='prompt',
            name='assigned_user_2_song_choice',
        ),
        migrations.RemoveField(
            model_name='prompt',
            name='assigned_user_2_votes',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_round',
        ),
        migrations.AddField(
            model_name='prompt',
            name='unique_id',
            field=models.CharField(default=api.models.generate_prompt_id, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='prompt',
            name='voting_round',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='main_round',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='room',
            name='num_players',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='prompts_per_player',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='room',
            name='voting_round',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default=api.models.generate_room_code, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='gamestate',
            field=models.CharField(choices=[('Q', 'Queue'), ('P', 'Prompt'), ('SEL', 'Select'), ('V', 'Vote'), ('SCR', 'Score')], default='Q', max_length=3),
        ),
    ]
