# Generated by Django 3.2.16 on 2023-09-10 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20230910_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promptassignments',
            name='prompt_unique_id',
            field=models.CharField(max_length=8),
        ),
    ]
