# Generated by Django 3.2.16 on 2023-09-10 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_promptassignments_prompt_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='unique_id',
            field=models.CharField(default='ABCD', max_length=10, unique=True),
        ),
    ]
