# Generated by Django 3.2.16 on 2023-09-10 05:05

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_prompt_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='unique_id',
            field=models.CharField(default=api.models.generate_prompt_id, max_length=10, unique=True),
        ),
    ]
