# Generated by Django 3.2.16 on 2023-11-17 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20231116_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='host_device_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='num_rounds',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='room',
            name='song_selection_timer',
            field=models.IntegerField(default=120),
        ),
    ]
