# Generated by Django 3.2.16 on 2023-11-17 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20231117_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='num_rounds',
            field=models.IntegerField(null=True),
        ),
    ]
