# Generated by Django 3.2.16 on 2023-11-18 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_room_num_rounds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='host_device_only',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='num_rounds',
            field=models.IntegerField(default=2),
        ),
    ]
