# Generated by Django 3.2.16 on 2023-12-05 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20231117_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='current_timer',
            field=models.IntegerField(null=True),
        ),
    ]
