# Generated by Django 3.2.16 on 2023-12-06 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_room_current_timer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prompt',
            old_name='prompt_key',
            new_name='main_round',
        ),
    ]
