# Generated by Django 3.2.16 on 2023-12-09 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_rename_prompt_key_prompt_main_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='promptassignments',
            name='song_artist',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='promptassignments',
            name='song_image_url',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='promptassignments',
            name='song_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
