# Generated by Django 3.2.16 on 2023-12-09 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20231209_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promptassignments',
            name='song_artist',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='promptassignments',
            name='song_image_url',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='promptassignments',
            name='song_title',
            field=models.TextField(null=True),
        ),
    ]
