# Generated by Django 3.2.16 on 2023-12-09 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20231209_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_unique_id', models.CharField(max_length=8)),
                ('voting_user', models.CharField(max_length=50, unique=True)),
                ('voted_for_user', models.CharField(max_length=50)),
            ],
        ),
    ]
