# Generated by Django 3.2.9 on 2023-01-09 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0002_alter_spotifytoken_refresh_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifytoken',
            name='refresh_token',
            field=models.CharField(default=None, max_length=150),
            preserve_default=False,
        ),
    ]
