# Generated by Django 3.2.16 on 2023-10-29 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0003_alter_spotifytoken_refresh_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersSpotify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, unique=True)),
                ('image_url', models.CharField(max_length=200)),
                ('display_name', models.CharField(max_length=50)),
                ('spotify_id', models.CharField(max_length=200)),
            ],
        ),
    ]
