# Generated by Django 3.2.16 on 2023-11-16 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0004_usersspotify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersspotify',
            name='image_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
